import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ClientInit from '@/components/ClientInit';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/sonner';
import { env } from '@/utils/env';
import './globals.css';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: env.appName,
  // TODO: add description
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <meta name='apple-mobile-web-app-title' content={env.appName} />
      </head>

      <body className='min-h-full flex flex-col'>
        <ClientInit />
        <ThemeProvider>
          {children}
          <Toaster position='bottom-center' />
        </ThemeProvider>
      </body>
    </html>
  );
}
